import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Welcome to Next + TypeScript Boilerplate (pages dir)</h1>
				<p>A boilerplate/starter project for quickly building web using Next with TypeScript</p>
			</main>
		</>
	);
}
